"use client";

import { useEffect, useMemo, useState } from "react";
import { PageHeader, Surface, Card, Button, Icon, Progress, StatusPill } from "@/components/dashboard/ui";
import { useSheet, SheetHeader } from "@/components/dashboard/sheet";
import {
  OPPORTUNITIES,
  OPP_CATEGORIES,
  STATUS_META,
  ANALYSIS_STEPS,
  statusOf,
  generateProposal,
  type Opportunity,
  type OppCategory,
} from "@/lib/firstinline";

const money = (n: number) => `€${n.toLocaleString()}`;

/* -------------------------------------------------------------------------- */
/*  AI Proposal Builder — analyze → editable proposal → copy/download/send      */
/* -------------------------------------------------------------------------- */

function ProposalBuilderSheet({ opp }: { opp: Opportunity }) {
  const { close } = useSheet();
  const [step, setStep] = useState(0);
  const [ready, setReady] = useState(false);
  const [text, setText] = useState("");
  const [copied, setCopied] = useState(false);
  const [sent, setSent] = useState(false);

  // Run the "analysis" then drop in the generated proposal.
  useEffect(() => {
    let s = 0;
    const tick = setInterval(() => {
      s += 1;
      setStep(s);
      if (s >= ANALYSIS_STEPS.length) {
        clearInterval(tick);
        setText(generateProposal(opp));
        setReady(true);
      }
    }, 500);
    return () => clearInterval(tick);
  }, [opp]);

  function copy() {
    navigator.clipboard?.writeText(text).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 1600);
  }
  function download() {
    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${opp.name.trim().replace(/\s+/g, "-").toLowerCase()}-proposal.md`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  if (!ready) {
    return (
      <div>
        <SheetHeader title="GRID AI is writing your proposal" subtitle={`Analyzing ${opp.name} — website, social, branding & content.`} />
        <div className="flex flex-col gap-2.5">
          {ANALYSIS_STEPS.map((label, i) => {
            const done = i < step;
            const active = i === step;
            return (
              <div key={label} className={`flex items-center gap-3 rounded-2xl border px-4 py-3 transition-colors ${done ? "border-review-gold/30 bg-review-gold/[0.06]" : active ? "border-white/15 bg-white/[0.04]" : "border-white/8 bg-white/[0.02]"}`}>
                <span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full ${done ? "bg-review-gold/15 text-review-gold ring-1 ring-review-gold/30" : "bg-white/[0.06] text-white/40"}`}>
                  {done ? <Icon name="check" size={15} /> : <Icon name="sparkles" size={14} className={active ? "animate-pulse" : ""} />}
                </span>
                <span className={`text-sm ${done ? "text-white" : active ? "text-white/80" : "text-white/40"}`}>{label}</span>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  if (sent) {
    return (
      <div className="py-4 text-center">
        <span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-escrow-green/15 text-escrow-green ring-1 ring-escrow-green/30">
          <Icon name="send" size={26} />
        </span>
        <h2 className="mt-5 text-xl font-semibold tracking-tight text-white">Proposal sent to {opp.name}</h2>
        <p className="mx-auto mt-2 max-w-xs text-sm leading-relaxed text-white/60">
          Sent to {opp.email}. You were first in line — we’ll notify you the moment they reply.
        </p>
        <div className="mt-6">
          <Button full tone="gold" onClick={close}>
            Done
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div>
      <SheetHeader title="AI Proposal Builder" subtitle={`${opp.name} · ${opp.category} · ${opp.location}`} />
      <div className="mb-3 flex flex-wrap items-center gap-2">
        <span className="inline-flex items-center gap-1.5 rounded-full bg-review-gold/12 px-2.5 py-1 text-[11px] font-medium text-review-gold ring-1 ring-review-gold/25">
          <Icon name="sparkles" size={12} /> Generated by GRID AI
        </span>
        <span className="text-[11px] text-white/40">Edit anything before you send.</span>
      </div>
      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        rows={14}
        className="w-full resize-none rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3 font-mono text-[12.5px] leading-relaxed text-white/85 outline-none transition-colors focus:border-review-gold/40"
      />
      <div className="mt-4 grid grid-cols-2 gap-2.5">
        <Button variant="ghost" onClick={copy}>
          <Icon name="file" size={15} /> {copied ? "Copied" : "Copy"}
        </Button>
        <Button variant="ghost" onClick={download}>
          <Icon name="download" size={15} /> Download
        </Button>
      </div>
      <div className="mt-2.5">
        <Button full tone="gold" arrow onClick={() => setSent(true)}>
          <Icon name="send" size={15} /> Send to {opp.name}
        </Button>
      </div>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/*  Opportunity card                                                           */
/* -------------------------------------------------------------------------- */

function DetailLine({ icon, children }: { icon: "globe" | "instagram" | "mail" | "user"; children: React.ReactNode }) {
  return (
    <div className="flex items-center gap-2 truncate font-mono text-xs text-white/55">
      <Icon name={icon} size={13} className="shrink-0 text-white/35" />
      <span className="truncate">{children}</span>
    </div>
  );
}

function OpportunityCard({ opp, onGenerate }: { opp: Opportunity; onGenerate: () => void }) {
  const status = statusOf(opp.contacted);
  const meta = STATUS_META[status];
  return (
    <Card className="flex flex-col p-5">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <h3 className="truncate text-lg font-semibold tracking-tight text-white">{opp.name.trim()}</h3>
          </div>
          <div className="mt-1 flex flex-wrap items-center gap-2">
            <span className="rounded-full bg-white/[0.06] px-2 py-0.5 text-[11px] font-medium text-white/70">{opp.category}</span>
            <span className="inline-flex items-center gap-1 text-xs text-white/45">
              <Icon name="pin" size={12} /> {opp.location}
            </span>
          </div>
        </div>
        <StatusPill tone={meta.tone} live={status === "first"}>
          {meta.dot} {meta.label}
        </StatusPill>
      </div>

      {/* Score + value */}
      <div className="mt-4 grid grid-cols-2 gap-3">
        <div className="rounded-2xl border border-white/8 bg-white/[0.02] p-3">
          <div className="flex items-baseline justify-between">
            <span className="text-[10px] uppercase tracking-[0.14em] text-white/40">Opp. score</span>
            <span className="font-mono text-lg font-semibold text-review-gold">{opp.score}</span>
          </div>
          <div className="mt-2">
            <Progress value={opp.score} tone="gold" />
          </div>
        </div>
        <div className="rounded-2xl border border-white/8 bg-white/[0.02] p-3">
          <div className="text-[10px] uppercase tracking-[0.14em] text-white/40">Potential value</div>
          <div className="mt-1 font-mono text-lg font-semibold text-white">{money(opp.value)}</div>
          <div className="mt-0.5 text-[11px] text-white/40">{opp.contacted} creators contacted</div>
        </div>
      </div>

      {/* Contact intel */}
      <div className="mt-4 grid grid-cols-1 gap-1.5 sm:grid-cols-2">
        <DetailLine icon="globe">{opp.website}</DetailLine>
        <DetailLine icon="instagram">{opp.instagram}</DetailLine>
        <DetailLine icon="mail">{opp.email}</DetailLine>
        {opp.contact && <DetailLine icon="user">{opp.contact}</DetailLine>}
      </div>

      <div className="mt-4 flex items-center justify-between border-t border-white/8 pt-4">
        <span className="inline-flex items-center gap-1.5 text-[11px] text-white/40">
          <Icon name="clock" size={12} /> Detected {opp.detected}
        </span>
        <Button tone="gold" arrow onClick={onGenerate} className="!py-2 !pl-4">
          Generate Proposal
        </Button>
      </div>
    </Card>
  );
}

/* -------------------------------------------------------------------------- */
/*  Page                                                                       */
/* -------------------------------------------------------------------------- */

type CatFilter = "All" | OppCategory;

export default function FirstInLinePage() {
  const { open } = useSheet();
  const [cat, setCat] = useState<CatFilter>("All");
  const [firstOnly, setFirstOnly] = useState(false);

  const results = useMemo(
    () =>
      OPPORTUNITIES.filter((o) => {
        const matchCat = cat === "All" || o.category === cat;
        const matchStatus = !firstOnly || statusOf(o.contacted) === "first";
        return matchCat && matchStatus;
      }),
    [cat, firstOnly],
  );

  const firstCount = OPPORTUNITIES.filter((o) => statusOf(o.contacted) === "first").length;
  const avgScore = Math.round(OPPORTUNITIES.reduce((a, o) => a + o.score, 0) / OPPORTUNITIES.length);
  const pipeline = OPPORTUNITIES.reduce((a, o) => a + o.value, 0);

  return (
    <div className="flex flex-col gap-8">
      <div className="rise">
        <PageHeader
          eyebrow="Create & earn"
          tone="gold"
          title="First In Line™"
          subtitle="AI-discovered businesses to reach before your competitors do."
        />
      </div>

      {/* Intelligence ticker */}
      <div className="rise grid grid-cols-2 gap-3 lg:grid-cols-4" style={{ animationDelay: "60ms" }}>
        {[
          { label: "Live opportunities", value: String(OPPORTUNITIES.length), tone: "text-white" },
          { label: "First in line", value: String(firstCount), tone: "text-escrow-green" },
          { label: "Avg. opp. score", value: String(avgScore), tone: "text-review-gold" },
          { label: "Pipeline value", value: money(pipeline), tone: "text-white" },
        ].map((s) => (
          <Surface key={s.label} radius="1.25rem" inner="p-4">
            <div className="text-[10px] uppercase tracking-[0.16em] text-white/40">{s.label}</div>
            <div className={`mt-1.5 font-mono text-2xl font-semibold tracking-tight ${s.tone}`}>{s.value}</div>
          </Surface>
        ))}
      </div>

      {/* Filters */}
      <div className="rise flex flex-wrap items-center gap-2" style={{ animationDelay: "120ms" }}>
        {(["All", ...OPP_CATEGORIES] as CatFilter[]).map((c) => (
          <button
            key={c}
            onClick={() => setCat(c)}
            className={`rounded-full px-3.5 py-1.5 text-sm font-medium transition-colors ${cat === c ? "bg-review-gold text-[#101114]" : "bg-white/[0.05] text-white/60 hover:text-white"}`}
          >
            {c}
          </button>
        ))}
        <button
          onClick={() => setFirstOnly((v) => !v)}
          className={`ml-auto inline-flex items-center gap-1.5 rounded-full px-3.5 py-1.5 text-sm font-medium transition-colors ${firstOnly ? "bg-escrow-green/15 text-escrow-green ring-1 ring-escrow-green/30" : "bg-white/[0.05] text-white/60 hover:text-white"}`}
        >
          <Icon name="target" size={14} /> First in line only
        </button>
      </div>

      {/* Opportunities */}
      <div className="rise grid gap-4 lg:grid-cols-2" style={{ animationDelay: "180ms" }}>
        {results.map((o) => (
          <OpportunityCard key={o.id} opp={o} onGenerate={() => open(<ProposalBuilderSheet opp={o} />)} />
        ))}
      </div>
      {results.length === 0 && (
        <Surface radius="2rem" inner="p-10">
          <p className="text-center text-sm text-white/55">No opportunities match this filter.</p>
        </Surface>
      )}
    </div>
  );
}
