"use client";

import { useState } from "react";
import { PageHeader, Surface, Button, Icon, StatusPill, Ring } from "@/components/dashboard/ui";
import { useSheet, SheetHeader } from "@/components/dashboard/sheet";
import { LEADS, money, type Lead } from "@/lib/createearn";

function genEmail(lead: Lead): string {
  const first = lead.name;
  return [
    `Subject: A visual edge for ${first}`,
    ``,
    `Hi ${first} team,`,
    ``,
    `I work with ${lead.category.toLowerCase()} brands to turn first impressions into bookings — cinematic stills and short films built for web and social.`,
    ``,
    `I'd love to put together a quick visual plan for ${first}. Worth a 15-minute call this week?`,
    ``,
    `Best,`,
    `John Hope · via Grid`,
  ].join("\n");
}

function genProposal(lead: Lead): string {
  const deposit = Math.round(lead.value * 0.5);
  return [
    `PROPOSAL — ${lead.name}`,
    ``,
    `A focused production to give ${lead.name} a premium, cohesive visual identity.`,
    ``,
    `SCOPE`,
    `• Pre-production & shot planning`,
    `• Half- to full-day shoot`,
    `• Edited stills + a 30–60s hero film`,
    `• Web + social exports, two revisions`,
    ``,
    `INVESTMENT`,
    `• Project rate: ${money(lead.value)}`,
    `• ${money(deposit)} on signing, ${money(deposit)} on approved delivery`,
    `• Protected by Grid Escrow`,
  ].join("\n");
}

function OutreachSheet({ lead, mode }: { lead: Lead; mode: "proposal" | "email" }) {
  const { close } = useSheet();
  const [text, setText] = useState(mode === "email" ? genEmail(lead) : genProposal(lead));
  const [copied, setCopied] = useState(false);
  const [sent, setSent] = useState(false);

  if (sent) {
    return (
      <div className="py-4 text-center">
        <span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-escrow-green/15 text-escrow-green ring-1 ring-escrow-green/30">
          <Icon name="send" size={26} />
        </span>
        <h2 className="mt-5 text-xl font-semibold tracking-tight text-white">{mode === "email" ? "Email sent" : "Proposal sent"}</h2>
        <p className="mx-auto mt-2 max-w-xs text-sm leading-relaxed text-white/60">Sent to {lead.email}. Follow-up reminder set for 3 days.</p>
        <div className="mt-6"><Button full onClick={close}>Done</Button></div>
      </div>
    );
  }

  return (
    <div>
      <SheetHeader title={mode === "email" ? "AI outreach email" : "AI proposal"} subtitle={`${lead.name} · ${lead.category}`} />
      <div className="mb-3 inline-flex items-center gap-1.5 rounded-full bg-grid-blue/12 px-2.5 py-1 text-[11px] font-medium text-aerial-cyan ring-1 ring-grid-blue/25">
        <Icon name="sparkles" size={12} /> Generated by GRID AI
      </div>
      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
        rows={mode === "email" ? 11 : 13}
        className="w-full resize-none rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3 font-mono text-[12.5px] leading-relaxed text-white/85 outline-none focus:border-grid-blue/40"
      />
      <div className="mt-4 grid grid-cols-2 gap-2.5">
        <Button variant="ghost" onClick={() => { navigator.clipboard?.writeText(text).catch(() => {}); setCopied(true); setTimeout(() => setCopied(false), 1500); }}>
          <Icon name="file" size={15} /> {copied ? "Copied" : "Copy"}
        </Button>
        <Button arrow onClick={() => setSent(true)}>
          <Icon name="send" size={15} /> Send
        </Button>
      </div>
    </div>
  );
}

function statusTone(s: Lead["proposal"]) {
  if (s === "Won") return "escrow" as const;
  if (s === "Sent" || s === "Negotiating") return "blue" as const;
  if (s === "Drafted") return "gold" as const;
  return "cyan" as const;
}

export default function SalesAssistantPage() {
  const { open } = useSheet();
  const pipeline = LEADS.reduce((a, l) => a + l.value, 0);
  const weighted = Math.round(LEADS.reduce((a, l) => a + (l.value * l.probability) / 100, 0));
  const avgProb = Math.round(LEADS.reduce((a, l) => a + l.probability, 0) / LEADS.length);
  const sent = LEADS.filter((l) => l.proposal === "Sent" || l.proposal === "Negotiating" || l.proposal === "Won").length;

  return (
    <div className="flex flex-col gap-8">
      <div className="rise">
        <PageHeader eyebrow="Create & earn" tone="blue" title="AI Sales Assistant™" subtitle="Every lead is a mission. Track, pitch and close from one console." />
      </div>

      {/* Mission control header */}
      <div className="rise" style={{ animationDelay: "60ms" }}>
        <Surface radius="2rem" inner="p-6">
          <div className="flex flex-col items-center gap-6 sm:flex-row">
            <div className="radar-scan relative flex h-28 w-28 shrink-0 items-center justify-center overflow-hidden rounded-full border border-grid-blue/30 bg-grid-blue/[0.05]">
              <span className="absolute h-20 w-20 rounded-full border border-white/10" />
              <span className="absolute h-12 w-12 rounded-full border border-white/10" />
              <Icon name="target" size={22} className="text-aerial-cyan" />
            </div>
            <div className="grid flex-1 grid-cols-2 gap-3 sm:grid-cols-4">
              {[
                { label: "Active missions", value: String(LEADS.length) },
                { label: "Pipeline", value: money(pipeline) },
                { label: "Weighted", value: money(weighted) },
                { label: "Proposals out", value: String(sent) },
              ].map((s) => (
                <div key={s.label} className="rounded-2xl border border-white/8 bg-white/[0.02] p-3">
                  <div className="text-[10px] uppercase tracking-[0.14em] text-white/40">{s.label}</div>
                  <div className="mt-1 font-mono text-lg font-semibold text-white">{s.value}</div>
                </div>
              ))}
            </div>
          </div>
        </Surface>
      </div>

      {/* Missions */}
      <div className="rise grid gap-4 lg:grid-cols-2" style={{ animationDelay: "120ms" }}>
        {LEADS.map((l) => (
          <div key={l.id} className="glass glass-hover rounded-3xl border border-white/10 p-5">
            <div className="flex items-start gap-4">
              <Ring value={l.probability} size={64} stroke={5} tone={l.probability >= 70 ? "escrow" : l.probability >= 50 ? "gold" : "red"}>
                <span className="font-mono text-sm font-semibold text-white">{l.probability}%</span>
              </Ring>
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <h3 className="truncate text-base font-semibold text-white">{l.name}</h3>
                  <span className={`h-2 w-2 shrink-0 rounded-full ${l.health === "hot" ? "bg-urgent-red" : l.health === "warm" ? "bg-review-gold" : "bg-white/30"}`} title={l.health} />
                </div>
                <div className="mt-0.5 text-xs text-white/50">{l.category} · last contact {l.lastContact}</div>
                <div className="mt-2 flex items-center gap-3">
                  <span className="font-mono text-lg font-semibold text-white">{money(l.value)}</span>
                  <StatusPill tone={statusTone(l.proposal)}>{l.proposal}</StatusPill>
                </div>
              </div>
            </div>
            <div className="mt-4 grid grid-cols-2 gap-2.5 border-t border-white/8 pt-4">
              <Button variant="ghost" onClick={() => open(<OutreachSheet lead={l} mode="email" />)} className="!py-2">
                <Icon name="mail" size={14} /> Email
              </Button>
              <Button arrow onClick={() => open(<OutreachSheet lead={l} mode="proposal" />)} className="!py-2 !pl-4">
                Proposal
              </Button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
